In [1]:
# import pandas

import pandas as pd

In [3]:
# import csv file

df = pd.read_csv('/Users/otis/Desktop/most_runs_odi.csv')
df

,Player,Span,Mat,Inns,NO,Runs,HS,Ave,BF,SR,100,50,0,4s,6s
0,SR Tendulkar (IND),1989-2012,463,452,41,18426,200*,44.83,21368.0,86.23,49,96,20,2016,195
1,KC Sangakkara (Asia/ICC/SL),2000-2015,404,380,41,14234,169,41.98,18048.0,78.86,25,93,15,1385,88
2,V Kohli (IND),2008-2023,292,280,44,13848,183,58.67,14797.0,93.58,50,72,16,1294,151
3,RT Ponting (AUS/ICC),1995-2012,375,365,39,13704,164,42.03,17046.0,80.39,30,82,20,1231,162
4,RT Ponting (AUS/ICC),1995-2012,375,365,39,13704,164,42.03,17046.0,80.39,30,82,20,1231,162
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,JP Duminy (SA),2004-2019,199,179,40,5117,150*,36.81,6052.0,84.55,4,27,7,347,75
97,PD Collingwood (ENG),2001-2011,197,181,37,5092,120*,35.36,6614.0,76.98,5,26,7,365,74
98,A Symonds (AUS),1998-2009,198,161,33,5088,156,39.75,5504.0,92.44,6,30,15,449,103
99,Abdul Razzaq (Asia/PAK),1996-2011,265,228,57,5080,112,29.70,6252.0,81.25,3,23,14,382,124
100,JC Buttler (ENG),2012-2023,181,154,27,5022,162*,39.54,4288.0,117.11,11,26,14,407,170

In [ ]:
# Rename columns